/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pokemon;
import javax.swing.ImageIcon;

/**
 *
 * @author FRANCISCOPESDEMELLO
 */
public class Iniciais1 extends javax.swing.JFrame {

    /**
     * Creates new form Iniciais1
     */
    public Iniciais1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campo1 = new javax.swing.JLabel();
        Fogo = new javax.swing.JButton();
        Agua = new javax.swing.JButton();
        Terra = new javax.swing.JButton();
        campo2 = new javax.swing.JLabel();
        campo3 = new javax.swing.JLabel();
        evo1 = new javax.swing.JButton();
        evo2 = new javax.swing.JButton();
        evo3 = new javax.swing.JButton();
        campo4 = new javax.swing.JLabel();
        sim = new javax.swing.JButton();
        nao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campo1.setText("Qual o tipo do seu Pokemon?");

        Fogo.setText("Fogo");
        Fogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FogoActionPerformed(evt);
            }
        });

        Agua.setText("Agua");
        Agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AguaActionPerformed(evt);
            }
        });

        Terra.setText("Terra");
        Terra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerraActionPerformed(evt);
            }
        });

        campo3.setText("Qual é a evolução ele está?");

        evo1.setText("Evolução 1");
        evo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evo1ActionPerformed(evt);
            }
        });

        evo2.setText("Evolução 2");
        evo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evo2ActionPerformed(evt);
            }
        });

        evo3.setText("Evolução 3");
        evo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evo3ActionPerformed(evt);
            }
        });

        campo4.setText("Ele é shiny?");

        sim.setText("Sim");
        sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simActionPerformed(evt);
            }
        });

        nao.setText("Não");
        nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(campo1)
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(Fogo)
                                .addGap(18, 18, 18)
                                .addComponent(Agua)
                                .addGap(18, 18, 18)
                                .addComponent(Terra))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(campo3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(evo1)
                                .addGap(18, 18, 18)
                                .addComponent(evo2)
                                .addGap(18, 18, 18)
                                .addComponent(evo3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(sim)
                                .addGap(28, 28, 28)
                                .addComponent(nao))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fogo)
                    .addComponent(Agua)
                    .addComponent(Terra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evo1)
                    .addComponent(evo2)
                    .addComponent(evo3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sim)
                    .addComponent(nao))
                .addGap(0, 190, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AguaActionPerformed
        // TODO add your handling code here:
        ImageIcon agua1 = new ImageIcon(getClass().getResource("Squirtle.png"));
        campo2.setIcon(agua1);
        tipo = "agua";
        
    }//GEN-LAST:event_AguaActionPerformed

    private void FogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FogoActionPerformed
        // TODO add your handling code here:
        ImageIcon fogo1 = new ImageIcon(getClass().getResource("Charmander.png"));
        campo2.setIcon(fogo1);
        tipo = "fogo";
        
    }//GEN-LAST:event_FogoActionPerformed

    private void TerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerraActionPerformed
        // TODO add your handling code here:
        ImageIcon terra1 = new ImageIcon(getClass().getResource("Bulbasaur.jfif"));
        campo2.setIcon(terra1);
        tipo = "planta";
        
    }//GEN-LAST:event_TerraActionPerformed

    private void evo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evo2ActionPerformed
        // TODO add your handling code here:
        if (tipo == "fogo"){
            ImageIcon fogo2 = new ImageIcon(getClass().getResource("Charmeleon.jfif"));
            campo2.setIcon(fogo2);
        } else if(tipo == "agua"){
            ImageIcon agua2 = new ImageIcon(getClass().getResource("Wartortle2.jfif"));
            campo2.setIcon(agua2);
        } else if(tipo == "planta"){
            ImageIcon terra2 = new ImageIcon(getClass().getResource("Ivysaur.jfif"));
            campo2.setIcon(terra2);
        }
        
        estagio = 2;
        
    }//GEN-LAST:event_evo2ActionPerformed

    private void evo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evo1ActionPerformed
        // TODO add your handling code here:
        if (tipo == "fogo"){
            ImageIcon fogo1 = new ImageIcon(getClass().getResource("Charmander.png"));
            campo2.setIcon(fogo1);
        } else if(tipo == "agua"){
            ImageIcon agua1 = new ImageIcon(getClass().getResource("Squirtle.png"));
            campo2.setIcon(agua1);
        } else if(tipo == "planta"){
            ImageIcon terra1 = new ImageIcon(getClass().getResource("Bulbasaur.jfif"));
            campo2.setIcon(terra1);
        }
        
        estagio = 1;
        
    }//GEN-LAST:event_evo1ActionPerformed

    private void evo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evo3ActionPerformed
        // TODO add your handling code here:
        if (tipo == "fogo"){
            ImageIcon fogo3 = new ImageIcon(getClass().getResource("Charizard.png"));
            campo2.setIcon(fogo3);
        } else if(tipo == "agua"){
            ImageIcon agua3 = new ImageIcon(getClass().getResource("Blastoise.jfif"));
            campo2.setIcon(agua3);
        } else if(tipo == "planta"){
            ImageIcon terra3 = new ImageIcon(getClass().getResource("Venusaur.jfif"));
            campo2.setIcon(terra3);
        }
        
        estagio = 3;
        
    }//GEN-LAST:event_evo3ActionPerformed

    private void simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simActionPerformed
        // TODO add your handling code here:
        ImageIcon fogo1s = new ImageIcon(getClass().getResource("Charmander2.jfif"));
        ImageIcon agua1s = new ImageIcon(getClass().getResource("Squirtle2.jfif"));
        ImageIcon terra1s = new ImageIcon(getClass().getResource("Bulbasaur2.jfif"));
        ImageIcon fogo2s = new ImageIcon(getClass().getResource("Charmeleon2.png"));
        ImageIcon agua2s = new ImageIcon(getClass().getResource("Wartortle.jfif"));
        ImageIcon terra2s = new ImageIcon(getClass().getResource("Ivysaur2.jfif"));
        ImageIcon fogo3s = new ImageIcon(getClass().getResource("Charizard2.jfif"));
        ImageIcon agua3s = new ImageIcon(getClass().getResource("Blastoise2.jfif"));
        ImageIcon terra3s = new ImageIcon(getClass().getResource("Venusaur2.jfif"));
        
        if(tipo == "fogo" && estagio == 1){
            campo2.setIcon(fogo1s);
        }else if(tipo == "fogo" && estagio == 2){
            campo2.setIcon(fogo2s);
        }else if(tipo == "fogo" && estagio == 3){
            campo2.setIcon(fogo3s);
        }else if(tipo == "agua" && estagio == 1){
            campo2.setIcon(agua1s);
        }else if(tipo == "agua" && estagio == 2){
            campo2.setIcon(agua2s);
        }else if(tipo == "agua" && estagio == 3){
            campo2.setIcon(agua3s);
        }else if(tipo == "planta" && estagio == 1){
            campo2.setIcon(terra1s);
        }else if(tipo == "planta" && estagio == 2){
            campo2.setIcon(terra2s);
        }else if(tipo == "planta" && estagio == 3){
            campo2.setIcon(terra3s);
        }
        
    }//GEN-LAST:event_simActionPerformed

    private void naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoActionPerformed
        // TODO add your handling code here:
        ImageIcon fogo1 = new ImageIcon(getClass().getResource("Charmander.png"));
        ImageIcon agua1 = new ImageIcon(getClass().getResource("Squirtle.png"));
        ImageIcon terra1 = new ImageIcon(getClass().getResource("Bulbasaur.jfif"));
        ImageIcon fogo2 = new ImageIcon(getClass().getResource("Charmeleon.jfif"));
        ImageIcon agua2 = new ImageIcon(getClass().getResource("Wartortle2.jfif"));
        ImageIcon terra2 = new ImageIcon(getClass().getResource("Ivysaur.jfif"));
        ImageIcon fogo3 = new ImageIcon(getClass().getResource("Charizard.png"));
        ImageIcon agua3 = new ImageIcon(getClass().getResource("Blastoise.jfif"));
        ImageIcon terra3 = new ImageIcon(getClass().getResource("Venusaur.jfif"));
        
        if(tipo == "fogo" && estagio == 1){
            campo2.setIcon(fogo1);
        }else if(tipo == "fogo" && estagio == 2){
            campo2.setIcon(fogo2);
        }else if(tipo == "fogo" && estagio == 3){
            campo2.setIcon(fogo3);
        }else if(tipo == "agua" && estagio == 1){
            campo2.setIcon(agua1);
        }else if(tipo == "agua" && estagio == 2){
            campo2.setIcon(agua2);
        }else if(tipo == "agua" && estagio == 3){
            campo2.setIcon(agua3);
        }else if(tipo == "planta" && estagio == 1){
            campo2.setIcon(terra1);
        }else if(tipo == "planta" && estagio == 2){
            campo2.setIcon(terra2);
        }else if(tipo == "planta" && estagio == 3){
            campo2.setIcon(terra3);
        }
        
    }//GEN-LAST:event_naoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciais1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciais1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciais1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciais1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciais1().setVisible(true);
            }
        });
    }
    
    String tipo;
    int estagio;
    Boolean shiny;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agua;
    private javax.swing.JButton Fogo;
    private javax.swing.JButton Terra;
    private javax.swing.JLabel campo1;
    private javax.swing.JLabel campo2;
    private javax.swing.JLabel campo3;
    private javax.swing.JLabel campo4;
    private javax.swing.JButton evo1;
    private javax.swing.JButton evo2;
    private javax.swing.JButton evo3;
    private javax.swing.JButton nao;
    private javax.swing.JButton sim;
    // End of variables declaration//GEN-END:variables
}
